ros__parameters:
  image: map.pgm                # Make sure this points correctly (relative path or absolute)
  resolution: 0.05              # 5cm per pixel
  origin: [-25.6, -25.6, 0.0]   # Center the map (assuming 1024x1024)
  negate: 0
  occupied_thresh: 0.65
  free_thresh: 0.196
  mode: trinary
