<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!--############################### Mathematical Constants ################################-->
    <xacro:property name="PI" value="3.14159265"/>
    <!--########################################################################################-->

    <!--###################################### Arguments #######################################-->
    <xacro:arg name="body_length" default="2.0" />
    <xacro:arg name="body_width" default="1.0" />
    <xacro:arg name="body_height" default="0.5" />
    <xacro:arg name="body_density" default="1000.0" />
    <xacro:arg name="wheel_radius" default="0.3" />
    <xacro:arg name="wheel_width" default="0.1" />
    <xacro:arg name="wheel_density" default="1000.0" />
    <xacro:arg name="max_steering_angle" default="0.6108" />
    <xacro:arg name="max_steering_angular_velocity" default="1.570796" />
    <xacro:arg name="max_steering_effort" default="1.0" />
    <xacro:arg name="max_velocity" default="1.0" />
    <xacro:arg name="max_effort" default="10.0" />
    <xacro:arg name="camera_box_size" default="0.1" />
    <xacro:arg name="camera_stick_size" default="0.2" />
    <xacro:arg name="camera_height" default="1.5" />
    <xacro:arg name="camera_pitch" default="0.1" />
    <xacro:arg name="camera_fov" default="90" />
    <xacro:arg name="camera_fps" default="30" />
    <xacro:arg name="image_width" default="640" />
    <xacro:arg name="image_height" default="480" />
    <!--########################################################################################-->

    <!--################################# Vehicle Properties ##################################-->
    <xacro:property name="body_length" value="$(arg body_length)"/>
    <xacro:property name="body_width" value="$(arg body_width)"/>
    <xacro:property name="body_height" value="$(arg body_height)"/>
    <xacro:property name="body_density" value="$(arg body_density)"/>
    <xacro:property name="wheel_radius" value="$(arg wheel_radius)"/>
    <xacro:property name="wheel_width" value="$(arg wheel_width)"/>
    <xacro:property name="wheel_density" value="$(arg wheel_density)"/>
    <xacro:property name="max_steering_angle" value="$(arg max_steering_angle)"/>
    <xacro:property name="max_steering_angular_velocity" value="$(arg max_steering_angular_velocity)"/>
    <xacro:property name="max_steering_effort" value="$(arg max_steering_effort)"/>
    <xacro:property name="max_velocity" value="$(arg max_velocity)"/>
    <xacro:property name="max_effort" value="$(arg max_effort)"/>
    <xacro:property name="camera_box_size" value="$(arg camera_box_size)"/>
    <xacro:property name="camera_stick_size" value="$(arg camera_stick_size)"/>
    <xacro:property name="camera_height" value="$(arg camera_height)"/>
    <xacro:property name="camera_pitch" value="$(arg camera_pitch)"/>
    <xacro:property name="camera_fov" value="$(arg camera_fov)"/>
    <xacro:property name="camera_fps" value="$(arg camera_fps)"/>
    <xacro:property name="image_width" value="$(arg image_width)"/>
    <xacro:property name="image_height" value="$(arg image_height)"/>
    
    <xacro:property name="body_mass" value="${body_density * body_length * body_height * body_width}"/>
    <xacro:property name="body_inertia_x" value="${1.0/12.0 * body_mass * (body_height*body_height + body_width*body_width)}"/>
    <xacro:property name="body_inertia_y" value="${1.0/12.0 * body_mass * (body_length*body_length + body_height*body_height)}"/>
    <xacro:property name="body_inertia_z" value="${1.0/12.0 * body_mass * (body_length*body_length + body_width*body_width)}"/>
    <xacro:property name="wheel_separation" value="${body_width + wheel_width}"/>
    <xacro:property name="wheel_offset" value="${body_length/2 - wheel_radius}"/>
    <xacro:property name="wheel_mass" value="${wheel_density * PI * wheel_radius * wheel_radius * wheel_width}"/>
    <xacro:property name="wheel_inertia_x" value="${1.0/12.0 * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
    <xacro:property name="wheel_inertia_y" value="${1.0/12.0 * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
    <xacro:property name="wheel_inertia_z" value="${1.0/2.0 * wheel_mass * wheel_radius * wheel_radius}"/>
    <xacro:property name="max_wheel_angular_velocity" value="${max_velocity / wheel_radius}"/>
    <!--########################################################################################-->

    <!-- ####################################### Macros ########################################-->
    <xacro:macro name="default_inertial" params="mass ixx ixy ixz iyy iyz izz xyz">
      <inertial>
        <origin xyz="${xyz}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
          ixx="${ixx}" ixy="${ixy}" ixz="${ixz}"
          iyy="${iyy}" iyz="${iyz}" izz="${izz}" />
      </inertial>
    </xacro:macro>
    
    <xacro:macro name="mesh_visual_collision" params="color mesh">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${mesh_path}/${mesh}"/>
        </geometry>
        <material name="">
          <color rgba="${color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${mesh_path}/${mesh}"/>
        </geometry>
      </collision>
    </xacro:macro>
    <!--########################################################################################-->
</robot>
