navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    delay: 0.1
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
    # datum: [29.3039, 30.8446, 44.2999] # pre-set datum if needed, [lat, lon, yaw]